### ISSUE TITLE
Cars and Vehicles 

### ISSUE THREAD

**Issue by Tengri2270** [Jigara/OGN-Roleplay#9]
Please check the following missing features in what order is more easy:

-Vehicles are missing the HUD for speed and gas, seatbelt , nothing shows up at the moment when you are in the car;
-There is no button for the seatbelt or we couldn't find one that activates it;
-Cars are still maxed out at 130 mph ;
-The tuner shop doesn't have an entrance to it so it probably has a missing interior

Tengri, 
Team OGN

**Comment by Jigara** [comment]
Hey Tengri,

- OG Car HUD is in the process of being finalized, NoPixel 3.0 inspired, will update once patched.
- Key: [**B**] will allow you to Enable/Disable your Seat-belt once the above system is implemented.
- Please detail the desired speed limit for configuration via reply in this discussion.
- Benny's Customs requires you to be of a Mechanic Job, in order to operate.

      🙏
Thank you,
Team OGN.

**Comment by Tengri2270** [comment]
Thank you!

-For the Car limit I would say 220mph and from there each car goes as fast as it can(until their limit)

Tengri,
Team OGN
